---
title: "Read + Clean Project Data"
author: "Cameron Jones"
date: "2023-11-19"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(rnaturalearth)
library(maps)
library(sf)
```

# Bird Locations

```{r}
# Downloaded from: https://www.sciencebase.gov/catalog/item/632b2d7bd34e71c6d67bc161
# These files are too big to upload to GitHub so you need to go download them yourself, run this chunk once, and then you'll have bird_locations.csv on your local machine.

# Read in raw bird data
birds = bind_rows(read_csv("NABBP_2022_grp_39.csv") %>% 
                    mutate(bird_type = "American Goldfinch"),
                  read_csv("NABBP_2022_grp_45.csv") %>% 
                    mutate(bird_type = "Song Sparrow"))

# Latitude range: 50-25N
# Longitude range: 125-65W
bird_locations = birds %>% 
  select(BAND, EVENT_DATE, EVENT_YEAR, EVENT_MONTH, LAT_DD, LON_DD, bird_type) %>% 
  mutate(
    EVENT_MONTH = as.numeric(EVENT_MONTH),
    EVENT_YEAR = as.numeric(EVENT_YEAR)
  ) %>% 
  filter(
    EVENT_YEAR >= 2000,
    LAT_DD <= 50 & LAT_DD >= 25, 
    LON_DD >= -125 & LON_DD <= -65
  )

# In the future, would like to exclude points which are outside the USA - will leave this for Milestone 3, having trouble with spatial features

write_csv(bird_locations, "bird_locations.csv")
```

```{r}
bird_locations = read_csv("bird_locations.csv")
```


# Dataset of State Temps

```{r}
# should only have to run this chunk once to generate allStateTemps.csv
cleanStateData = function(fileName) {
  fileLocation = paste0("./StateData/", fileName)
  stateName = str_remove(fileName, "\\.csv") %>% str_to_title()
  
  return(
    read_csv(fileLocation, skip = 3) %>% 
      mutate(
        year = substr(Date, 1, 4) %>% as.numeric(),
        month_num = substr(Date, 5, 6) %>% as.numeric(),
        month_lab = month_num %>% month(label = TRUE),
        name = stateName
      )  
  )
}

stateTemps = map_dfr(list.files("./StateData"), cleanStateData)
write_csv(stateTemps, "allStateTemps.csv")
```

```{r}
stateTemps = read_csv("allStateTemps.csv")
```

# State polygon objects for spatial plotting

```{r}
statePolygons = ne_states(country = "united states of america", returnclass = "sf") %>% filter(!(name %in% c("Alaska", "Hawaii", "District of Columbia")))
```


# Plotting Function

```{r}
graphingFunction = function(g_data, b_data, m, y) {
    ggplot(g_data) + 
      geom_sf(aes(fill = Value)) +
      geom_point(data = b_data,
                 mapping = aes(x = LON_DD, y = LAT_DD, color = bird_type),
                 size = 3) +
      scale_color_manual(values = c("gold", "burlywood4")) +
      scale_fill_viridis_c(option = "inferno", limits = c(0, 100)) +
      labs(
        title = "Bird Sightings and Average Temperature",
        subtitle = paste(month(m, label = TRUE, abbr = FALSE), y),
        fill = "Avg. Temp (F)",
        color = "Bird Type"
      ) +
    theme_void()
}


graphWrapper = function(yearInput, monthInput) {
  graphingData = left_join(statePolygons, 
                           stateTemps %>% 
                             filter(year == yearInput,
                                    month_num == monthInput)
                           )
    

  bird_locations_selected = bird_locations %>% 
    filter(EVENT_YEAR == yearInput,
           EVENT_MONTH == monthInput)
  
  return(graphingFunction(graphingData, bird_locations_selected, monthInput, yearInput))
}
```

# Example

```{r}
graphWrapper(2022, 1)
```
