---
title: "Read + Clean Project Data"
author: "Cameron Jones"
date: "2023-10-12"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(rnaturalearth)
library(maps)
library(sf)
```

# Bird Locations

```{r}
# Downloaded from: https://www.sciencebase.gov/catalog/item/632b2d7bd34e71c6d67bc161
birds = bind_rows(read_csv("NABBP_2022_grp_01.csv"), read_csv("NABBP_2022_grp_07.csv"))
```

```{r}
# identify birds which appear five or more times so we can actually plot meaningful movement
five_or_more = birds %>% filter(EVENT_YEAR >= 2000) %>% count(BAND) %>% filter(n >= 5)
```

```{r}
# Latitude range: 50-25N
# Longitude range: 125-65W
bird_locations = birds %>% 
  filter(
    BAND %in% five_or_more$BAND, # keep birds identified above
    EVENT_YEAR >= 2000, # limiting to this century
    LAT_DD <= 50 & LAT_DD >= 25, # only locations in the contiguous United States for now
    LON_DD >= -125 & LON_DD <= -65
  ) %>% 
  select(BAND, EVENT_DATE, EVENT_YEAR, EVENT_MONTH, LAT_DD, LON_DD) %>% 
  mutate(EVENT_MONTH = as.numeric(EVENT_MONTH))
```

# Dataset of State Temps

```{r}
# downloaded from: https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/statewide/time-series/3/tavg/all/1/2000-2023
# (had to input different parameters and save each time)

# may eventually have to download all fifty manually... this is the only way I could get this to work

alabama = read_csv("alabama.csv", skip = 3) %>%
  mutate(
    year = substr(Date, 1, 4) %>% as.numeric(),
    month_num = substr(Date, 5, 6) %>% as.numeric(),
    month_lab = month_num %>% month(label = TRUE),
    name = "Alabama"
  )

texas = read_csv("texas.csv", skip = 3) %>%
  mutate(
    year = substr(Date, 1, 4) %>% as.numeric(),
    month_num = substr(Date, 5, 6) %>% as.numeric(),
    month_lab = month_num %>% month(label = TRUE),
    name = "Texas"
  )

arkansas = read_csv("arkansas.csv", skip = 3) %>%
  mutate(
    year = substr(Date, 1, 4) %>% as.numeric(),
    month_num = substr(Date, 5, 6) %>% as.numeric(),
    month_lab = month_num %>% month(label = TRUE),
    name = "Arkansas"
  )

stateTemps = bind_rows(alabama, texas, arkansas)
```

# state polygon objects for spatial plotting

```{r}
statePolygons = ne_states(country = "united states of america", returnclass = "sf")
```


# Plotting Function

```{r}
snapshotTempGraph = function(yearInput, monthInput) {
  graphingData = left_join(statePolygons, 
                           stateTemps %>% filter(year == yearInput, month_num == monthInput)) %>% filter(!(name %in% c("Alaska", "Hawaii", "District of Columbia")))

  return(
    ggplot(graphingData) + 
      geom_sf(aes(fill = Value)) +
      geom_point(data = bird_locations %>% filter(EVENT_YEAR == yearInput, EVENT_MONTH == monthInput), mapping = aes(x = LON_DD, y = LAT_DD), color = "red", size = 4) + 
      labs(
        title = "Bird Sightings and Average Temperature",
        subtitle = paste(month.abb[monthInput], yearInput),
        fill = "Avg. Temp (F)"
      )
  )
}
```

# Example

```{r}
snapshotTempGraph(2006, 11)
```

